spring:
  application:
    name: uni-cafe-springboot

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uni_cafe?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: infinity@Han


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: 192.168.10.128
      port: 6379
      database: 0
      timeout: 3000

wechat:
  appid: wx6d87f0e18085ff2f
  secret: 03946ee5c86226d11ed210ffa24c388e

server:
  port: 9000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.han.cafe.entity

jackson:
  time-zone: Asia/Shanghai
  date-format: yyyy-MM-dd HH:mm:ss

jwt:
  secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c6b5d0f1e2
  expiration: 86400000  # 24小时
